### ISSUE TITLE
Performance improvement of specific use case: displaying a grid of integer values

### ISSUE THREAD

**Issue by ramiromagno** [coolbutuseless/nara#1]
Hi Mike,

Thanks for developing such a really nice package.

I'd like to ask if you think we could make this use case of mine more performant.

I'd like to use `{nara}` to display the simulation of cellular automata in real-time.

Here is a toy example:

```R
library(nara)
n_colours <- 5
my_palette <- hsv(seq(0, 1, length.out = n_colours))
w <- 100
h <- 100


for (i in 1:20) {
  m <-
    matrix(data = sample(seq_len(n_colours), size = w * h, replace = TRUE),
           nrow = h)
  m2 <- matrix(my_palette[m], nrow = h)
  nr <- raster_to_nr(m2)
  grid.raster(nr, interpolate = FALSE)
  Sys.sleep(0.1)
}
```

Assume that `m` holds the state of the cellular automaton, i.e. an integer matrix that comprises only of positive integer values, starting at 1.  For illustrative purposes I'm randomly generating these values with `sample()`. Assume also that I have a color palette that maps each integer state value to a colour (as provided by the vector `my_palette`).

Would there be a more performant way (a shortcut, or perhaps a solution based on C code) to go from my matrix `m` to the `nativeRaster` object `nr` that would obviate the calls:

1. `m2 <- matrix(my_palette[m], nrow = h)`
2. `nr <- raster_to_nr(m2)`

Thanks once again for developing such nice projects!

**Comment by coolbutuseless** [comment]
Added `matrix_to_nr()`

For the example benchmark below, using `matrix_to_nr()` is 50x to 70x faster than doing a manual lookup to get a raster then using `raster_to_nr()`

Note: `raster_to_nr()` is currently plain R, and will be replaced by a C version before release.


|expression                                        |   itr/sec|
|:-------------------------------------------------|---------:|
|{ raster_to_nr(matrix(my_palette[m], nrow = h)) } |  1198|
|matrix_to_nr(m, my_palette)                       | 63509|
|matrix_to_nr(m, my_palette, dst)                  | 88790|

```
  n_colours <- 5
  my_palette <- hsv(seq(0, 1, length.out = n_colours))
  w <- 200
  h <- 100

  m <- matrix(data = sample(seq_len(n_colours), size = w * h, replace = TRUE), nrow = h)
  
  dst <- nr_new(w, h);
  
  bench::mark(
    {matrix(my_palette[m], nrow = h) |> raster_to_nr()},
    matrix_to_nr(m, my_palette),
    matrix_to_nr(m, my_palette, dst)
  )
```
