### ISSUE TITLE
Shiny integration

### ISSUE THREAD

**Issue by ekianjo** [coolbutuseless/nara#11]
Simple question, but can this be integrated in a shiny application?

**Comment by coolbutuseless** [comment]
You could possibly display a static raster image using "renderImage()".

Not too sure what else you want to do with a nativeRaster image in shiny

**Comment by ekianjo** [comment]
My idea is to potentially interact with the rendered image by using Shiny controls (buttons or other inputs). 
But that would be only for static rendering? Could you render frames at the max framerate without waiting for shiny inputs?

**Comment by coolbutuseless** [comment]
This type of shiny/nara interaction is not possible. sorry.
