### ISSUE TITLE
`colour_to_integer()` for `"transparent"` and `NA_character_` "colors"

### ISSUE THREAD

**Issue by trevorld** [coolbutuseless/nara#13]
I'm observing that `colour_to_integer()` is casting "transparent" to an opaque color equivalent to "white" (with a message saying unknown color) and is casting `NA_character_` to "#00000000" which is a fully transparent value but a slightly different fully transparent value from what `col2rgb()` assigns to it.  I'd *pedantically* "expect" `colour_to_integer(NA_character_)` to instead return `16777215L` (the same as `colour_to_integer("#FFFFFF00")`).

```r
> library("nara")
> colour_to_integer("#FFFFFF00") |> integer_to_colour()
[1] "#ffffff00"
> colour_to_integer("transparent") |> integer_to_colour()
Unknown colour: transparent
[1] "#ffffffff"
> colour_to_integer(NA_character_) |> integer_to_colour()
[1] "#00000000"
> col2rgb(c("transparent", "#FFFFFF00", NA_character_, "white"),  
          alpha = TRUE)
      [,1] [,2] [,3] [,4]
red    255  255  255  255
green  255  255  255  255
blue   255  255  255  255
alpha    0    0    0  255
```

I've observed that `farver::encode_native()` also has trouble with these two edge cases: https://github.com/thomasp85/farver/issues/47

**Comment by trevorld** [comment]
My understanding is that some graphic devices or image viewers don't support alpha transparency so this would be the difference between a "transparent" background being rendered "white" or "black" in such devices/programs...

**Comment by coolbutuseless** [comment]
Thanks for raising the issue.

`transparent` and `NA_character` now return the integer for `#ffffff00`
