### ISSUE TITLE
is 4 channel mandatory? 

### ISSUE THREAD

**Issue by mdsumner** [coolbutuseless/nara#16]
in my first implementation reading nativeRaster from spatial sources I made 3-channel the default. 

but

```R
Error in nr_line(im[[1]], segs[, 1], segs[, 2], segs[, 3], segs[, 4]) : 
  Object is not a nativeRaster with 4 channels
```

Can this be relaxed to allow 3 channels as well? 

(Maybe I shouldn't have done this, but the code for 3 or 4 is in R)

**Comment by coolbutuseless** [comment]
4-channel is all I have at the moment, so it's all I've tested with.  The sanity check for 4-channels is for when someone finally needs it and I might have to think about it :)

I'd be grateful an example of a 3-channel nativeraster.  How are you creating it?

Questions which I've avoided until now regarding 3-channel nativerasters:

* What's the memory layout for 3-channel RGB native raster?   
    * Is it still packed into a 4 byte integer?
    * If its a sequence of 3bytes e.g. rgbrgbrgbrgb (with 4 colours in 3 integers) then this probably would never be supported as internally the colours are handled using a `uint32_t`
    * If it's a sequence of 4bytes, what is the alpha byte set to?  Does it default to `0xff`?  Or is it random depending on who initialized the memory?
    * Do different methods for creating 3-channel nativerasterss create nativerasters with different alpha bytes?
* Just write a C func to normalise the alpha byte?

**Comment by mdsumner** [comment]
Created here, I just copied the macros in R, I wanted Byte(x1,x3,x4)->nativeRaster without returning to R: 

https://github.com/hypertidy/vapour/blob/c913e9552be002d3d78483a6d504f047e019d988/inst/include/gdalraster/gdalraster.h#L71

```R
## imagery source
dsn <- "<GDAL_WMS><Service name=\"VirtualEarth\"><ServerUrl>http://a${server_num}.ortho.tiles.virtualearth.net/tiles/a${quadkey}.jpeg?g=90</ServerUrl></Service><MaxConnections>4</MaxConnections><Cache/></GDAL_WMS>"
library(vapour)
im <- gdal_raster_nara(dsn, target_dim = c(256, 256))
#'nativeRaster' int [1:256, 1:256] -14214910 -14214910 ...
#- attr(*, "channels")= int 3

```

That's vapour from hypertidy/vapour - need to be a bit cautious atm because I'm chasing down some CRAN problems, so attached as file here. 


[vapour_list_nara.rds.zip](https://github.com/user-attachments/files/15687771/vapour_list_nara.rds.zip)

**Comment by mdsumner** [comment]
Thanks!  I've been on slow boil with this but being able to draw on these is amazing!!!

**Comment by mdsumner** [comment]
Also I haven't addressed your questions, I need to spend some time on thosee

**Comment by coolbutuseless** [comment]
from that `vapour_list` object, it appears that the 3-byte nativeraster:

* is actually 4 bytes
* All alpha bytes set to 0xFF

I've just now updated the code to allow 3-channel native rasters.  It looks sane on your example.   let me know if it looks weird on anything else.

**Comment by mdsumner** [comment]
Cool!  Thanks

**Comment by coolbutuseless** [comment]
Thanks for raising the issue and the example object.

Closing this issue as done. 

Open up a fresh issue if there are particular issues with 3-channel nativerasters

The thing I'm most expecting to happen is that some application/pathway/package won't clear out the alpha byte and it will be filled with random garbage.  Unlikely, but possible.
