### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by ramiromagno** [coolbutuseless/nara#2]
I think it could be interesting to benchmark against the solutions tried here: https://stackoverflow.com/questions/48119360/performant-2d-opengl-graphics-in-r-for-fast-display-of-raster-image-using-qtpain

**Comment by coolbutuseless** [comment]
I'm not at all keen to install qt, opengl or sdl to benchmark speeds.    And by the looks of it, none of those "solutions" is actually implemented.

One things that makes matrices "slow" to render, is that they always need to be converted into a display friendly format.   {nara} works around this issue by rendering direct to the display friendly format.

I did in fact write a wrapper to SDL a few years ago and got good rendering speeds ~100fps (e.g. https://twitter.com/coolbutuseless/status/1281183539506143235?s=20&t=8yiNLRYLCYAnNoYuDf829A).  But it was too much work to maintain.

The issue with linking to these big C libraries is that they are a huge burden to create and maintain - and they are not easy for users to install and use either!

I'm closing this as a "WONT DO" - but would be interested to read any benchmarks that others come up.
