### ISSUE TITLE
does the `"channels"` attribute make any difference in `nativeRaster` objects?

### ISSUE THREAD

**Issue by ramiromagno** [coolbutuseless/nara#4]
It seems that the `"channels"` attribute can be completely omiited, as the code below works fine showing a red square:

```r
m <- matrix(rep(colour_to_integer("#ff0000ff"), 1), nrow = 1)
class(m) <- "nativeRaster"
grid.newpage()
grid.raster(m, interpolate = FALSE)

```

**Comment by coolbutuseless** [comment]
It doesn't seem to have an effect. 

The `channel` attribute is added by both  `png::readPNG(..., native = TRUE)` and `jpeg::readJPEG(..., native = TRUE)`, so I will too just in case there's some deep reason it should be there
