### ISSUE TITLE
Movement in first example is jerky for me

### ISSUE THREAD

**Issue by tomwenseleers** [coolbutuseless/nara#9]
On my Windows system the movement of the first example was jerky for me - it would only actually display a frame every second or so... To fix that, I had to insert a dev.hold() and dev.flush() call in the for loop as below...

```
library(grid)

# Setup a fast graphics device that can render quickly
x11(type = 'dbcairo', antialias = 'none')
dev.control('inhibit')

# Create the in-memory nativeRaster canvas
nr <- nr_new(100, 30, 'grey80')

# Clear, blit and render => animation!
for (i in -30:110) { 
    dev.hold()
    nr_fill(nr, 'grey80')                    # Clear the nativeRaster
    nr_blit(nr, dino[[(i %% 16) + 1]], i, 1) # copy dino to nativeRaster
    grid.raster(nr, interpolate = FALSE)     # copy nativeRaster to screen
    Sys.sleep(0.02)   # Stop animation running too fast.
    dev.flush()                          
}
```

**Comment by coolbutuseless** [comment]
I see this too.  The windows() device (which is used when `x11()` is called on windows) is double buffered and seems to require explicit hold/flush operations to look sane.

Adding `dev.hold()`/`dev.flush()` works (as you've done here.  But this demo also works smoothly if the `x11()` call is replaced with

`windows(buffered = FALSE)`.

Thanks for the report. I'll update the demo code.
